# Config file

# DATES
MONTH: 5
YEAR: 2024

# TRIP
MIN_DAYS: 0
MAX_DAYS: 30

# AIRPORTS
START_AIRPORT: IDK
END_AIRPORT: IDK

# SKYSCANNER SETTINGS
CURRENCY: 'USD'
LOCALE: 'en-US'
REGION: 'US'
DOMAIN: 'com'
